name: Apropriacao

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '15 18,20,21 * * 1,2,3,4,5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        chromedriver-version: '99.0.4844.51'
        java-version: '1.8'
        server-id: github 
        settings-path: ${{ github.workspace }} 
        
    - name: Install Google Chrome
    
        - run:|
          
               VERSION_STRING="99.0.4844.51"
               wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${VERSION_STRING}_amd64.deb"
               sudo dpkg -i "google-chrome-stable_${VERSION_STRING}_amd64.deb"
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml test
