name: Apropriacao

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 18,20,23 * * 1,2,3,4,5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: browser-actions/setup-chrome@latest
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
    
        
      with:
        chromedriver-version: '99.0.4844.51'
        java-version: '1.8'
        server-id: github 
        settings-path: ${{ github.workspace }} 


    - name: Build with Maven
      run: mvn -B package --file pom.xml test
